# Your project's server will run on proxy
PROXY: "http://localhost/tsa_redesign/web/"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Path to source folder
  src: "assets/src"
  # Paths to fonts
  fonts:
    - "vendor/bower-asset/font-awesome/fonts/**/*"
    - "vendor/bower-asset/bootstrap/fonts/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "vendor/bower-asset/bootstrap-sass/assets/stylesheets"
    - "vendor/bower-asset/font-awesome/scss"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    - "vendor/bower-asset/jquery/dist/jquery.js"
    - "vendor/twbs/bootstrap/dist/js/bootstrap.js"
