# Your project's server will run on proxy
PROXY: "http://localhost/tsa_redesign/web/"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist/js"
  # Path to source folder
  src: "assets/src/js"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    - "vendor/bower-asset/jquery/dist/jquery.js"
    - "vendor/bower-asset/jquery-ui/jquery-ui.js"
    - "vendor/twbs/bootstrap/dist/js/bootstrap.bundle.js"
